imageName: spm-ui-upgrade-helper
runArgs: -p 3000:3000 -p 4000-4002:4000-4002
repoFolder: spm-ui-upgrade-helper
repoUrl: wh-govspm-docker-local.artifactory.swg-devops.com/artifactory/wh-govspm-docker-local
