imageName: spm-ui-upgrade-helper_upgradehelper
imageNameBeanparser: spm-ui-upgrade-helper_beanparser
imageNameNodefront: spm-ui-upgrade-helper_nodefront
runArgs: -p 3000:3000 -p 4000-4004:4000-4004
username: ibmcom