language: node_js
node_js:
  - 12
group: bluezone
dist: xenial

env:
  - VER=`node -pe "require('./package.json')['version']"`

jobs:
  include:
    - stage: build
      script:
        - yarn install-all
        - yarn test
    - stage: deploy-gatsby-docs
      if: branch = main
      script:
        - cd packages/gatsby-docs && yarn install && yarn gatsby:deploy
