language: node_js
node_js:
  - 12
group: bluezone
dist: xenial

env:
  - VER=`node -pe "require('./package.json')['version']"`
jobs:
  include:
    - name: "Tests"
      script:
        - yarn install-all
        - yarn test
    - name: "Docs"
      script:
        - cd packages/gatsby-docs && yarn install-all
        - yarn gatsby:conditional-deploy
