language: node_js
node_js:
  - 12
group: bluezone
dist: xenial

env:
  - VER=`node -pe "require('./package.json')['version']"`

script:
  - yarn install-all
  - yarn test

deploy:
  - provider: script
    script: cd packages/gatsby-docs && yarn install && yarn gatsby:conditional-deploy
    on:
      branch: main

