language: node_js
node_js:
  - 12
group: bluezone
dist: xenial

env:
  - VER=`node -pe "require('./package.json')['version']"`

jobs:
  - stage: Tests
      script:
        - yarn install-all
        - yarn test
  
    - stage: spm_v8_tab_test_cpts
      if: branch = main AND type = cron
      install:
        - yarn install-all
        - npm ci
      script:
        - cd packages/gatsby-docs && yarn gatsby:conditional-deploy

  