language: node_js
node_js:
  - 12
group: bluezone
dist: xenial

env:
  - VER=`node -pe "require('./package.json')['version']"`


stages:
  - tests
  - documentation

# JOB CONFIGURATION
validate_common: &validate_common
  script:
    - yarn install-all
    - yarn test
validate_documentation: &validate_documentation
  script:
    - yarn test
    - cd packages/gatsby-docs && yarn gatsby:conditional-deploy

# EXTRA BUILD JOBS
jobs:
  include:
    - stage: tests
      <<: *validate_common
    - stage: documentation
      if: branch =~ ^main(_\S.\S.\S)?$|^release/v.*$|^feature/.*fluxy$ AND type = push
      <<: *validate_documentation