language: node_js
node_js:
  - 12
group: bluezone
dist: xenial

env:
  - VER=`node -pe "require('./package.json')['version']"`

script:
  - yarn install
  - yarn install-all
  - yarn test

services:
  - docker

deploy:
  provider: script
  script: node release.sh
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^v.*$
