language: node_js
node_js:
  - 12
group: bluezone
dist: xenial

env:
  - VER=`node -pe "require('./package.json')['version']"`

script:
  - cd packages/shared-utils
  - yarn install
  - yarn test
  - cd ../css-rules-engine
  - yarn install
  - yarn test
  - cd ../js-rules-engine
  - yarn install
  - yarn test
  - cd ../../docs
  - yarn install
  - yarn github-pages-deploy
