language: node_js
node_js:
  - 12
group: bluezone
dist: xenial

env:
  - VER=`node -pe "require('./package.json')['version']"`

script:
  - node -v
  - yarn -v
  - yarn install
  - yarn install-all
  - cd ./packages/css-rules-engine
  - yarn test
  - cd ../js-rules-engine
  - yarn test
