name: Deploy
uses: srepollock/gatsby-gh-pages-action@v2.2.0

on: 
push:
  branches: [main]
pull_request:
workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: macos-12
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 12
      - name: Install dependencies
        run: | 
          yarn install-all
          yarn run build
      - name: Deploy to Github packages
        # only deploy when pushing to main
        if: ${{(github.event_name == 'push' || github.event_name == 'workflow_dispatch' ) && github.ref_name == 'main'}}
        run: |
          cd ./public
          git init
          git config user.name ${{ github.actor }}
          git config user.email ${{ github.actor }}@users.noreply.github.com
          git add .
          git commit -m "Deploy commit: ${{ github.sha }}"
          git push -f https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}.git main:gh-pages
          echo 'Finished deploying the site.'

